apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: king-cluster-admin-binding
subjects:
- kind: ServiceAccount
  name: king
  namespace: ts
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io